/*
 * This file is generated by jOOQ.
 */
package it.barusu.tutorial.jooq.generator.tables.daos;


import it.barusu.tutorial.jooq.generator.tables.SchemaVersion;
import it.barusu.tutorial.jooq.generator.tables.records.SchemaVersionRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaVersionDao extends DAOImpl<SchemaVersionRecord, it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion, String> {

    /**
     * Create a new SchemaVersionDao without any configuration
     */
    public SchemaVersionDao() {
        super(SchemaVersion.SCHEMA_VERSION, it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion.class);
    }

    /**
     * Create a new SchemaVersionDao with an attached configuration
     */
    public SchemaVersionDao(Configuration configuration) {
        super(SchemaVersion.SCHEMA_VERSION, it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion.class, configuration);
    }

    @Override
    public String getId(it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion object) {
        return object.getVersion();
    }

    /**
     * Fetch records that have <code>version_rank BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfVersionRank(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.VERSION_RANK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version_rank IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByVersionRank(Integer... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.VERSION_RANK, values);
    }

    /**
     * Fetch records that have <code>installed_rank BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfInstalledRank(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>installed_rank IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByInstalledRank(Integer... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfVersion(String lowerInclusive, String upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByVersion(String... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.VERSION, values);
    }

    /**
     * Fetch a unique record that has <code>version = value</code>
     */
    public it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion fetchOneByVersion(String value) {
        return fetchOne(SchemaVersion.SCHEMA_VERSION.VERSION, value);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByDescription(String... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfType(String lowerInclusive, String upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByType(String... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.TYPE, values);
    }

    /**
     * Fetch records that have <code>script BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfScript(String lowerInclusive, String upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.SCRIPT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>script IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByScript(String... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.SCRIPT, values);
    }

    /**
     * Fetch records that have <code>checksum BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfChecksum(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.CHECKSUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>checksum IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByChecksum(Integer... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.CHECKSUM, values);
    }

    /**
     * Fetch records that have <code>installed_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfInstalledBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.INSTALLED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>installed_by IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByInstalledBy(String... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.INSTALLED_BY, values);
    }

    /**
     * Fetch records that have <code>installed_on BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfInstalledOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.INSTALLED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>installed_on IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByInstalledOn(LocalDateTime... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.INSTALLED_ON, values);
    }

    /**
     * Fetch records that have <code>execution_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfExecutionTime(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.EXECUTION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>execution_time IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchByExecutionTime(Integer... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.EXECUTION_TIME, values);
    }

    /**
     * Fetch records that have <code>success BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchRangeOfSuccess(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(SchemaVersion.SCHEMA_VERSION.SUCCESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>success IN (values)</code>
     */
    public List<it.barusu.tutorial.jooq.generator.tables.pojos.SchemaVersion> fetchBySuccess(Byte... values) {
        return fetch(SchemaVersion.SCHEMA_VERSION.SUCCESS, values);
    }
}
