/*
 * This file is generated by jOOQ.
 */
package it.barusu.tutorial.jooq.generator;


import it.barusu.tutorial.jooq.generator.tables.PUser;
import it.barusu.tutorial.jooq.generator.tables.SchemaVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HjParcel extends SchemaImpl {

    private static final long serialVersionUID = -261082650;

    /**
     * The reference instance of <code>hj_parcel</code>
     */
    public static final HjParcel HJ_PARCEL = new HjParcel();

    /**
     * The table <code>hj_parcel.p_user</code>.
     */
    public final PUser P_USER = it.barusu.tutorial.jooq.generator.tables.PUser.P_USER;

    /**
     * The table <code>hj_parcel.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = it.barusu.tutorial.jooq.generator.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private HjParcel() {
        super("hj_parcel", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            PUser.P_USER,
            SchemaVersion.SCHEMA_VERSION);
    }
}
