/*
 * This file is generated by jOOQ.
 */
package it.barusu.tutorial.jooq.generator;


import it.barusu.tutorial.jooq.generator.tables.PUser;
import it.barusu.tutorial.jooq.generator.tables.SchemaVersion;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>hj_parcel</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index P_USER_PRIMARY = Indexes0.P_USER_PRIMARY;
    public static final Index SCHEMA_VERSION_PRIMARY = Indexes0.SCHEMA_VERSION_PRIMARY;
    public static final Index SCHEMA_VERSION_SCHEMA_VERSION_IR_IDX = Indexes0.SCHEMA_VERSION_SCHEMA_VERSION_IR_IDX;
    public static final Index SCHEMA_VERSION_SCHEMA_VERSION_S_IDX = Indexes0.SCHEMA_VERSION_SCHEMA_VERSION_S_IDX;
    public static final Index SCHEMA_VERSION_SCHEMA_VERSION_VR_IDX = Indexes0.SCHEMA_VERSION_SCHEMA_VERSION_VR_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index P_USER_PRIMARY = Internal.createIndex("PRIMARY", PUser.P_USER, new OrderField[] { PUser.P_USER.ID }, true);
        public static Index SCHEMA_VERSION_PRIMARY = Internal.createIndex("PRIMARY", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.VERSION }, true);
        public static Index SCHEMA_VERSION_SCHEMA_VERSION_IR_IDX = Internal.createIndex("schema_version_ir_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK }, false);
        public static Index SCHEMA_VERSION_SCHEMA_VERSION_S_IDX = Internal.createIndex("schema_version_s_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.SUCCESS }, false);
        public static Index SCHEMA_VERSION_SCHEMA_VERSION_VR_IDX = Internal.createIndex("schema_version_vr_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.VERSION_RANK }, false);
    }
}
