/*
 * This file is generated by jOOQ.
 */
package it.barusu.tutorial.jooq.generator;


import it.barusu.tutorial.jooq.generator.tables.PUser;
import it.barusu.tutorial.jooq.generator.tables.SchemaVersion;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in hj_parcel
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>hj_parcel.p_user</code>.
     */
    public static final PUser P_USER = PUser.P_USER;

    /**
     * The table <code>hj_parcel.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;
}
