/*
 * This file is generated by jOOQ.
 */
package it.barusu.tutorial.jooq.generator.tables.records;


import it.barusu.tutorial.jooq.generator.tables.PUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PUserRecord extends UpdatableRecordImpl<PUserRecord> implements Record6<Long, String, String, Long, String, Long> {

    private static final long serialVersionUID = 1674794727;

    /**
     * Setter for <code>hj_parcel.p_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hj_parcel.p_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hj_parcel.p_user.login_name</code>.
     */
    public void setLoginName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hj_parcel.p_user.login_name</code>.
     */
    public String getLoginName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hj_parcel.p_user.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hj_parcel.p_user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hj_parcel.p_user.version</code>.
     */
    public void setVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>hj_parcel.p_user.version</code>.
     */
    public Long getVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>hj_parcel.p_user.real_name</code>.
     */
    public void setRealName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hj_parcel.p_user.real_name</code>.
     */
    public String getRealName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hj_parcel.p_user.age</code>.
     */
    public void setAge(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>hj_parcel.p_user.age</code>.
     */
    public Long getAge() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, Long, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, Long, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PUser.P_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return PUser.P_USER.LOGIN_NAME;
    }

    @Override
    public Field<String> field3() {
        return PUser.P_USER.USER_NAME;
    }

    @Override
    public Field<Long> field4() {
        return PUser.P_USER.VERSION;
    }

    @Override
    public Field<String> field5() {
        return PUser.P_USER.REAL_NAME;
    }

    @Override
    public Field<Long> field6() {
        return PUser.P_USER.AGE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLoginName();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public Long component4() {
        return getVersion();
    }

    @Override
    public String component5() {
        return getRealName();
    }

    @Override
    public Long component6() {
        return getAge();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLoginName();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public Long value4() {
        return getVersion();
    }

    @Override
    public String value5() {
        return getRealName();
    }

    @Override
    public Long value6() {
        return getAge();
    }

    @Override
    public PUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PUserRecord value2(String value) {
        setLoginName(value);
        return this;
    }

    @Override
    public PUserRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public PUserRecord value4(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public PUserRecord value5(String value) {
        setRealName(value);
        return this;
    }

    @Override
    public PUserRecord value6(Long value) {
        setAge(value);
        return this;
    }

    @Override
    public PUserRecord values(Long value1, String value2, String value3, Long value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PUserRecord
     */
    public PUserRecord() {
        super(PUser.P_USER);
    }

    /**
     * Create a detached, initialised PUserRecord
     */
    public PUserRecord(Long id, String loginName, String userName, Long version, String realName, Long age) {
        super(PUser.P_USER);

        set(0, id);
        set(1, loginName);
        set(2, userName);
        set(3, version);
        set(4, realName);
        set(5, age);
    }
}
