/*
 * This file is generated by jOOQ.
 */
package it.barusu.tutorial.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PUser implements Serializable {

    private static final long serialVersionUID = -39185102;

    private Long   id;
    private String loginName;
    private String userName;
    private Long   version;
    private String realName;
    private Long   age;

    public PUser() {}

    public PUser(PUser value) {
        this.id = value.id;
        this.loginName = value.loginName;
        this.userName = value.userName;
        this.version = value.version;
        this.realName = value.realName;
        this.age = value.age;
    }

    public PUser(
        Long   id,
        String loginName,
        String userName,
        Long   version,
        String realName,
        Long   age
    ) {
        this.id = id;
        this.loginName = loginName;
        this.userName = userName;
        this.version = version;
        this.realName = realName;
        this.age = age;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public Long getAge() {
        return this.age;
    }

    public void setAge(Long age) {
        this.age = age;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PUser (");

        sb.append(id);
        sb.append(", ").append(loginName);
        sb.append(", ").append(userName);
        sb.append(", ").append(version);
        sb.append(", ").append(realName);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
